### ISSUE TITLE
Add variables to steps

### ISSUE THREAD

**Issue by RickardAhlstedt** [RickardAhlstedt/cicd-go#1]
# Add variables to steps

Example:
```yaml
steps:
  - name: "lint current file"
  command: "lint $FILE"
  if: "flags.watch=true"
```

This should only apply when watching folders, as the program listens for changed files.

Suggested variables:
| Variable | Desc. |
|--------|--------|
| `$FILE` | Current file that the eventlistener fired on (when using -watch) |
| `$CWD` | Current working directory | 
| `$EVENT_TYPE` | Type of fs-event (when using -watch) |
| `$EXT` | Extension of `$FILE` (when using -watch) |
| `$BASENAME` | Base name of the file without directory or extension (when using -watch) |
| `$DIRNAME` | Directory containing the file (when using -watch) |
| `$RELFILE` | The relative path to `$CWD` (when using -watch) |
| `$BUILD_FILE` | Path to the build-file in use |
| `$BUILD_STEP` | The current step name being executed (optional but helpful for logging) |
| `$TIMESTAMP` | Timestamp of the pipeline run |
| `$UUID` | Unique ID for the pipeline run |
| `$OS` | Current OS (linux, darwin, windows) |
| `$ARCH` | The current architecture (ARM64, x86, AMD64, etc.) |
| `$GIT_BRANCH` | Current git-branch |
| `$GIT_COMMIT` | Latest commit-hash |

We should also allow user-defined vars
```yaml
vars:
  ENV: "dev"
  OUT_DIR: "dist"
```
They can later be referenced as `$ENV`, `$OUT_DIR`, etc.
